ERM-1539: change labels
folio-org/ui-local-kb-admin pull request #161
Opened 2021-02-05 10:55 UTC by peterboehm

2021-02-05 14:59 UTC, aditya-matukumalli requested changes

2021-02-05 14:59 UTC, aditya-matukumalli commented on src/components/views/JobInfo.js
> +                      <KeyValue label={<FormattedMessage id="ui-local-kb-admin.jobtype" />}>
```suggestion
                      <KeyValue label={<FormattedMessage id="ui-local-kb-admin.jobType" />}>
```

2021-02-05 14:59 UTC, aditya-matukumalli commented on translations/ui-local-kb-admin/en.json
> +  "jobtype": "Job Type",
```suggestion
  "jobType": "Job Type",
```

2021-02-05 15:11 UTC, peterboehm commented on translations/ui-local-kb-admin/en.json
> +  "jobtype": "Job Type",
I made the change

2021-02-09 16:00 UTC, aditya-matukumalli approved these changes

2021-02-09 16:08 UTC, merged